name: Changesets Release

on:
  push:
    branches:
      - main

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        token: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.12.4
        run_install: false

    - name: Use Node.js 20.12.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.12.1
        registry-url: https://registry.npmjs.org/
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: ESLint
      run: pnpm run lint

    - name: Typecheck
      run: pnpm run typecheck

    - name: Run test
      run: pnpm run test

    - name: Run Audit
      run: pnpm audit --audit-level high

    - name: Build components
      run: pnpm run build

    - name: Create release PR or publish to npm
      id: changesets
      uses: changesets/action@v1.4.8
      with:
        publish: pnpm changeset publish
        title: Release packages [publish docs]
        commit: Release packages [publish docs]
        createGithubReleases: true
      env:
        GITHUB_TOKEN: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
        GIT_AUTHOR_NAME: imodeljs-admin
        GIT_AUTHOR_EMAIL: imodeljs-admin@users.noreply.github.com
        GIT_COMMITTER_NAME: imodeljs-admin
        GIT_COMMITTER_EMAIL: imodeljs-admin@users.noreply.github.com

    - name: Log Changesets Outputs
      run: |
        echo "Published: ${{ steps.changesets.outputs.published }}"
        echo "Published Packages: ${{ steps.changesets.outputs.publishedPackages }}"
        echo "Has Changesets: ${{ steps.changesets.outputs.hasChangesets }}"
        echo "Pull Request Number: ${{ steps.changesets.outputs.pullRequestNumber }}"
